---
- name: Apt update cache
  apt:
    update_cache: yes

- name: Installing python3 and pip
  apt:
    name: "{{ PYTHON_PACKAGES }}"
    update_cache: yes

- name: Installing awscli
  pip:
    name: awscli
    state: latest
    executable: pip3